/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandGuidelinesRouteImport } from './routes/brand-guidelines'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as HooksRouteImport } from './routes/hooks'
import { Route as LibsRouteImport } from './routes/libs'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsComposedRouteImport } from './routes/components/composed'
import { Route as ComponentsIconsRouteImport } from './routes/components/icons'
import { Route as ComponentsIntegrationsRouteImport } from './routes/components/integrations'
import { Route as ComponentsPrimitivesRouteImport } from './routes/components/primitives'
import { Route as ComponentsComposedAccordionRouteImport } from './routes/components/composed/accordion'
import { Route as ComponentsComposedActionModalRouteImport } from './routes/components/composed/action-modal'
import { Route as ComponentsComposedBannerRouteImport } from './routes/components/composed/banner'
import { Route as ComponentsComposedCalloutRouteImport } from './routes/components/composed/callout'
import { Route as ComponentsComposedDialogRouteImport } from './routes/components/composed/dialog'
import { Route as ComponentsComposedDrawerRouteImport } from './routes/components/composed/drawer'
import { Route as ComponentsComposedDropdownRouteImport } from './routes/components/composed/dropdown'
import { Route as ComponentsComposedFileUploadRouteImport } from './routes/components/composed/file-upload'
import { Route as ComponentsComposedHoverCardRouteImport } from './routes/components/composed/hover-card'
import { Route as ComponentsComposedMessageBubbleRouteImport } from './routes/components/composed/message-bubble'
import { Route as ComponentsComposedMetricInputRouteImport } from './routes/components/composed/metric-input'
import { Route as ComponentsComposedPasswordStrengthMeterRouteImport } from './routes/components/composed/password-strength-meter'
import { Route as ComponentsComposedPopoverRouteImport } from './routes/components/composed/popover'
import { Route as ComponentsComposedScrollAreaRouteImport } from './routes/components/composed/scroll-area'
import { Route as ComponentsComposedTabsRouteImport } from './routes/components/composed/tabs'
import { Route as ComponentsComposedToastRouteImport } from './routes/components/composed/toast'
import { Route as ComponentsComposedTooltipRouteImport } from './routes/components/composed/tooltip'
import { Route as ComponentsIntegrationsDataTableRouteImport } from './routes/components/integrations/data-table'
import { Route as ComponentsPrimitivesBadgeRouteImport } from './routes/components/primitives/badge'
import { Route as ComponentsPrimitivesBarsRouteImport } from './routes/components/primitives/bars'
import { Route as ComponentsPrimitivesBoxRouteImport } from './routes/components/primitives/box'
import { Route as ComponentsPrimitivesButtonRouteImport } from './routes/components/primitives/button'
import { Route as ComponentsPrimitivesCheckboxRouteImport } from './routes/components/primitives/checkbox'
import { Route as ComponentsPrimitivesCountBadgeRouteImport } from './routes/components/primitives/count-badge'
import { Route as ComponentsPrimitivesDisplayRouteImport } from './routes/components/primitives/display'
import { Route as ComponentsPrimitivesDividerRouteImport } from './routes/components/primitives/divider'
import { Route as ComponentsPrimitivesGridRouteImport } from './routes/components/primitives/grid'
import { Route as ComponentsPrimitivesHeadingRouteImport } from './routes/components/primitives/heading'
import { Route as ComponentsPrimitivesInputRouteImport } from './routes/components/primitives/input'
import { Route as ComponentsPrimitivesListRouteImport } from './routes/components/primitives/list'
import { Route as ComponentsPrimitivesProgressBarRouteImport } from './routes/components/primitives/progress-bar'
import { Route as ComponentsPrimitivesRadioRouteImport } from './routes/components/primitives/radio'
import { Route as ComponentsPrimitivesRowRouteImport } from './routes/components/primitives/row'
import { Route as ComponentsPrimitivesSelectRouteImport } from './routes/components/primitives/select'
import { Route as ComponentsPrimitivesSliderRouteImport } from './routes/components/primitives/slider'
import { Route as ComponentsPrimitivesStackRouteImport } from './routes/components/primitives/stack'
import { Route as ComponentsPrimitivesStatusDotRouteImport } from './routes/components/primitives/status-dot'
import { Route as ComponentsPrimitivesSwitchRouteImport } from './routes/components/primitives/switch'
import { Route as ComponentsPrimitivesTableRouteImport } from './routes/components/primitives/table'
import { Route as ComponentsPrimitivesTextRouteImport } from './routes/components/primitives/text'
import { Route as ComponentsPrimitivesTextareaRouteImport } from './routes/components/primitives/textarea'
import { Route as ComponentsPrimitivesVerifiedBadgeRouteImport } from './routes/components/primitives/verified-badge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandGuidelinesRoute = BrandGuidelinesRouteImport.update({
  id: '/brand-guidelines',
  path: '/brand-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksRoute = HooksRouteImport.update({
  id: '/hooks',
  path: '/hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const LibsRoute = LibsRouteImport.update({
  id: '/libs',
  path: '/libs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsComposedRoute = ComponentsComposedRouteImport.update({
  id: '/composed',
  path: '/composed',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsIconsRoute = ComponentsIconsRouteImport.update({
  id: '/icons',
  path: '/icons',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsIntegrationsRoute = ComponentsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsPrimitivesRoute = ComponentsPrimitivesRouteImport.update({
  id: '/primitives',
  path: '/primitives',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsComposedAccordionRoute =
  ComponentsComposedAccordionRouteImport.update({
    id: '/accordion',
    path: '/accordion',
    getParentRoute: () => ComponentsComposedRoute,
  } as any)
const ComponentsComposedActionModalRoute =
  ComponentsComposedActionModalRouteImport.update({
    id: '/action-modal',
    path: '/action-modal',
    getParentRoute: () => ComponentsComposedRoute,
  } as any)
const ComponentsComposedBannerRoute =
  ComponentsComposedBannerRouteImport.update({
    id: '/banner',
    path: '/banner',
    getParentRoute: () => ComponentsComposedRoute,
  } as any)
const ComponentsComposedCalloutRoute =
  ComponentsComposedCalloutRouteImport.update({
    id: '/callout',
    path: '/callout',
    getParentRoute: () => ComponentsComposedRoute,
  } as any)
const ComponentsComposedDialogRoute =
  ComponentsComposedDialogRouteImport.update({
    id: '/dialog',
    path: '/dialog',
    getParentRoute: () => ComponentsComposedRoute,
  } as any)
const ComponentsComposedDrawerRoute =
  ComponentsComposedDrawerRouteImport.update({
    id: '/drawer',
    path: '/drawer',
    getParentRoute: () => ComponentsComposedRoute,
  } as any)
const ComponentsComposedDropdownRoute =
  ComponentsComposedDropdownRouteImport.update({
    id: '/dropdown',
    path: '/dropdown',
    getParentRoute: () => ComponentsComposedRoute,
  } as any)
const ComponentsComposedFileUploadRoute =
  ComponentsComposedFileUploadRouteImport.update({
    id: '/file-upload',
    path: '/file-upload',
    getParentRoute: () => ComponentsComposedRoute,
  } as any)
const ComponentsComposedHoverCardRoute =
  ComponentsComposedHoverCardRouteImport.update({
    id: '/hover-card',
    path: '/hover-card',
    getParentRoute: () => ComponentsComposedRoute,
  } as any)
const ComponentsComposedMessageBubbleRoute =
  ComponentsComposedMessageBubbleRouteImport.update({
    id: '/message-bubble',
    path: '/message-bubble',
    getParentRoute: () => ComponentsComposedRoute,
  } as any)
const ComponentsComposedMetricInputRoute =
  ComponentsComposedMetricInputRouteImport.update({
    id: '/metric-input',
    path: '/metric-input',
    getParentRoute: () => ComponentsComposedRoute,
  } as any)
const ComponentsComposedPasswordStrengthMeterRoute =
  ComponentsComposedPasswordStrengthMeterRouteImport.update({
    id: '/password-strength-meter',
    path: '/password-strength-meter',
    getParentRoute: () => ComponentsComposedRoute,
  } as any)
const ComponentsComposedPopoverRoute =
  ComponentsComposedPopoverRouteImport.update({
    id: '/popover',
    path: '/popover',
    getParentRoute: () => ComponentsComposedRoute,
  } as any)
const ComponentsComposedScrollAreaRoute =
  ComponentsComposedScrollAreaRouteImport.update({
    id: '/scroll-area',
    path: '/scroll-area',
    getParentRoute: () => ComponentsComposedRoute,
  } as any)
const ComponentsComposedTabsRoute = ComponentsComposedTabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => ComponentsComposedRoute,
} as any)
const ComponentsComposedToastRoute = ComponentsComposedToastRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => ComponentsComposedRoute,
} as any)
const ComponentsComposedTooltipRoute =
  ComponentsComposedTooltipRouteImport.update({
    id: '/tooltip',
    path: '/tooltip',
    getParentRoute: () => ComponentsComposedRoute,
  } as any)
const ComponentsIntegrationsDataTableRoute =
  ComponentsIntegrationsDataTableRouteImport.update({
    id: '/data-table',
    path: '/data-table',
    getParentRoute: () => ComponentsIntegrationsRoute,
  } as any)
const ComponentsPrimitivesBadgeRoute =
  ComponentsPrimitivesBadgeRouteImport.update({
    id: '/badge',
    path: '/badge',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesBarsRoute =
  ComponentsPrimitivesBarsRouteImport.update({
    id: '/bars',
    path: '/bars',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesBoxRoute = ComponentsPrimitivesBoxRouteImport.update({
  id: '/box',
  path: '/box',
  getParentRoute: () => ComponentsPrimitivesRoute,
} as any)
const ComponentsPrimitivesButtonRoute =
  ComponentsPrimitivesButtonRouteImport.update({
    id: '/button',
    path: '/button',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesCheckboxRoute =
  ComponentsPrimitivesCheckboxRouteImport.update({
    id: '/checkbox',
    path: '/checkbox',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesCountBadgeRoute =
  ComponentsPrimitivesCountBadgeRouteImport.update({
    id: '/count-badge',
    path: '/count-badge',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesDisplayRoute =
  ComponentsPrimitivesDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesDividerRoute =
  ComponentsPrimitivesDividerRouteImport.update({
    id: '/divider',
    path: '/divider',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesGridRoute =
  ComponentsPrimitivesGridRouteImport.update({
    id: '/grid',
    path: '/grid',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesHeadingRoute =
  ComponentsPrimitivesHeadingRouteImport.update({
    id: '/heading',
    path: '/heading',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesInputRoute =
  ComponentsPrimitivesInputRouteImport.update({
    id: '/input',
    path: '/input',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesListRoute =
  ComponentsPrimitivesListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesProgressBarRoute =
  ComponentsPrimitivesProgressBarRouteImport.update({
    id: '/progress-bar',
    path: '/progress-bar',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesRadioRoute =
  ComponentsPrimitivesRadioRouteImport.update({
    id: '/radio',
    path: '/radio',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesRowRoute = ComponentsPrimitivesRowRouteImport.update({
  id: '/row',
  path: '/row',
  getParentRoute: () => ComponentsPrimitivesRoute,
} as any)
const ComponentsPrimitivesSelectRoute =
  ComponentsPrimitivesSelectRouteImport.update({
    id: '/select',
    path: '/select',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesSliderRoute =
  ComponentsPrimitivesSliderRouteImport.update({
    id: '/slider',
    path: '/slider',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesStackRoute =
  ComponentsPrimitivesStackRouteImport.update({
    id: '/stack',
    path: '/stack',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesStatusDotRoute =
  ComponentsPrimitivesStatusDotRouteImport.update({
    id: '/status-dot',
    path: '/status-dot',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesSwitchRoute =
  ComponentsPrimitivesSwitchRouteImport.update({
    id: '/switch',
    path: '/switch',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesTableRoute =
  ComponentsPrimitivesTableRouteImport.update({
    id: '/table',
    path: '/table',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesTextRoute =
  ComponentsPrimitivesTextRouteImport.update({
    id: '/text',
    path: '/text',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesTextareaRoute =
  ComponentsPrimitivesTextareaRouteImport.update({
    id: '/textarea',
    path: '/textarea',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)
const ComponentsPrimitivesVerifiedBadgeRoute =
  ComponentsPrimitivesVerifiedBadgeRouteImport.update({
    id: '/verified-badge',
    path: '/verified-badge',
    getParentRoute: () => ComponentsPrimitivesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-guidelines': typeof BrandGuidelinesRoute
  '/components': typeof ComponentsRouteWithChildren
  '/forms': typeof FormsRoute
  '/hooks': typeof HooksRoute
  '/libs': typeof LibsRoute
  '/playground': typeof PlaygroundRoute
  '/providers': typeof ProvidersRoute
  '/components/composed': typeof ComponentsComposedRouteWithChildren
  '/components/icons': typeof ComponentsIconsRoute
  '/components/integrations': typeof ComponentsIntegrationsRouteWithChildren
  '/components/primitives': typeof ComponentsPrimitivesRouteWithChildren
  '/components/': typeof ComponentsIndexRoute
  '/components/composed/accordion': typeof ComponentsComposedAccordionRoute
  '/components/composed/action-modal': typeof ComponentsComposedActionModalRoute
  '/components/composed/banner': typeof ComponentsComposedBannerRoute
  '/components/composed/callout': typeof ComponentsComposedCalloutRoute
  '/components/composed/dialog': typeof ComponentsComposedDialogRoute
  '/components/composed/drawer': typeof ComponentsComposedDrawerRoute
  '/components/composed/dropdown': typeof ComponentsComposedDropdownRoute
  '/components/composed/file-upload': typeof ComponentsComposedFileUploadRoute
  '/components/composed/hover-card': typeof ComponentsComposedHoverCardRoute
  '/components/composed/message-bubble': typeof ComponentsComposedMessageBubbleRoute
  '/components/composed/metric-input': typeof ComponentsComposedMetricInputRoute
  '/components/composed/password-strength-meter': typeof ComponentsComposedPasswordStrengthMeterRoute
  '/components/composed/popover': typeof ComponentsComposedPopoverRoute
  '/components/composed/scroll-area': typeof ComponentsComposedScrollAreaRoute
  '/components/composed/tabs': typeof ComponentsComposedTabsRoute
  '/components/composed/toast': typeof ComponentsComposedToastRoute
  '/components/composed/tooltip': typeof ComponentsComposedTooltipRoute
  '/components/integrations/data-table': typeof ComponentsIntegrationsDataTableRoute
  '/components/primitives/badge': typeof ComponentsPrimitivesBadgeRoute
  '/components/primitives/bars': typeof ComponentsPrimitivesBarsRoute
  '/components/primitives/box': typeof ComponentsPrimitivesBoxRoute
  '/components/primitives/button': typeof ComponentsPrimitivesButtonRoute
  '/components/primitives/checkbox': typeof ComponentsPrimitivesCheckboxRoute
  '/components/primitives/count-badge': typeof ComponentsPrimitivesCountBadgeRoute
  '/components/primitives/display': typeof ComponentsPrimitivesDisplayRoute
  '/components/primitives/divider': typeof ComponentsPrimitivesDividerRoute
  '/components/primitives/grid': typeof ComponentsPrimitivesGridRoute
  '/components/primitives/heading': typeof ComponentsPrimitivesHeadingRoute
  '/components/primitives/input': typeof ComponentsPrimitivesInputRoute
  '/components/primitives/list': typeof ComponentsPrimitivesListRoute
  '/components/primitives/progress-bar': typeof ComponentsPrimitivesProgressBarRoute
  '/components/primitives/radio': typeof ComponentsPrimitivesRadioRoute
  '/components/primitives/row': typeof ComponentsPrimitivesRowRoute
  '/components/primitives/select': typeof ComponentsPrimitivesSelectRoute
  '/components/primitives/slider': typeof ComponentsPrimitivesSliderRoute
  '/components/primitives/stack': typeof ComponentsPrimitivesStackRoute
  '/components/primitives/status-dot': typeof ComponentsPrimitivesStatusDotRoute
  '/components/primitives/switch': typeof ComponentsPrimitivesSwitchRoute
  '/components/primitives/table': typeof ComponentsPrimitivesTableRoute
  '/components/primitives/text': typeof ComponentsPrimitivesTextRoute
  '/components/primitives/textarea': typeof ComponentsPrimitivesTextareaRoute
  '/components/primitives/verified-badge': typeof ComponentsPrimitivesVerifiedBadgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-guidelines': typeof BrandGuidelinesRoute
  '/forms': typeof FormsRoute
  '/hooks': typeof HooksRoute
  '/libs': typeof LibsRoute
  '/playground': typeof PlaygroundRoute
  '/providers': typeof ProvidersRoute
  '/components/composed': typeof ComponentsComposedRouteWithChildren
  '/components/icons': typeof ComponentsIconsRoute
  '/components/integrations': typeof ComponentsIntegrationsRouteWithChildren
  '/components/primitives': typeof ComponentsPrimitivesRouteWithChildren
  '/components': typeof ComponentsIndexRoute
  '/components/composed/accordion': typeof ComponentsComposedAccordionRoute
  '/components/composed/action-modal': typeof ComponentsComposedActionModalRoute
  '/components/composed/banner': typeof ComponentsComposedBannerRoute
  '/components/composed/callout': typeof ComponentsComposedCalloutRoute
  '/components/composed/dialog': typeof ComponentsComposedDialogRoute
  '/components/composed/drawer': typeof ComponentsComposedDrawerRoute
  '/components/composed/dropdown': typeof ComponentsComposedDropdownRoute
  '/components/composed/file-upload': typeof ComponentsComposedFileUploadRoute
  '/components/composed/hover-card': typeof ComponentsComposedHoverCardRoute
  '/components/composed/message-bubble': typeof ComponentsComposedMessageBubbleRoute
  '/components/composed/metric-input': typeof ComponentsComposedMetricInputRoute
  '/components/composed/password-strength-meter': typeof ComponentsComposedPasswordStrengthMeterRoute
  '/components/composed/popover': typeof ComponentsComposedPopoverRoute
  '/components/composed/scroll-area': typeof ComponentsComposedScrollAreaRoute
  '/components/composed/tabs': typeof ComponentsComposedTabsRoute
  '/components/composed/toast': typeof ComponentsComposedToastRoute
  '/components/composed/tooltip': typeof ComponentsComposedTooltipRoute
  '/components/integrations/data-table': typeof ComponentsIntegrationsDataTableRoute
  '/components/primitives/badge': typeof ComponentsPrimitivesBadgeRoute
  '/components/primitives/bars': typeof ComponentsPrimitivesBarsRoute
  '/components/primitives/box': typeof ComponentsPrimitivesBoxRoute
  '/components/primitives/button': typeof ComponentsPrimitivesButtonRoute
  '/components/primitives/checkbox': typeof ComponentsPrimitivesCheckboxRoute
  '/components/primitives/count-badge': typeof ComponentsPrimitivesCountBadgeRoute
  '/components/primitives/display': typeof ComponentsPrimitivesDisplayRoute
  '/components/primitives/divider': typeof ComponentsPrimitivesDividerRoute
  '/components/primitives/grid': typeof ComponentsPrimitivesGridRoute
  '/components/primitives/heading': typeof ComponentsPrimitivesHeadingRoute
  '/components/primitives/input': typeof ComponentsPrimitivesInputRoute
  '/components/primitives/list': typeof ComponentsPrimitivesListRoute
  '/components/primitives/progress-bar': typeof ComponentsPrimitivesProgressBarRoute
  '/components/primitives/radio': typeof ComponentsPrimitivesRadioRoute
  '/components/primitives/row': typeof ComponentsPrimitivesRowRoute
  '/components/primitives/select': typeof ComponentsPrimitivesSelectRoute
  '/components/primitives/slider': typeof ComponentsPrimitivesSliderRoute
  '/components/primitives/stack': typeof ComponentsPrimitivesStackRoute
  '/components/primitives/status-dot': typeof ComponentsPrimitivesStatusDotRoute
  '/components/primitives/switch': typeof ComponentsPrimitivesSwitchRoute
  '/components/primitives/table': typeof ComponentsPrimitivesTableRoute
  '/components/primitives/text': typeof ComponentsPrimitivesTextRoute
  '/components/primitives/textarea': typeof ComponentsPrimitivesTextareaRoute
  '/components/primitives/verified-badge': typeof ComponentsPrimitivesVerifiedBadgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand-guidelines': typeof BrandGuidelinesRoute
  '/components': typeof ComponentsRouteWithChildren
  '/forms': typeof FormsRoute
  '/hooks': typeof HooksRoute
  '/libs': typeof LibsRoute
  '/playground': typeof PlaygroundRoute
  '/providers': typeof ProvidersRoute
  '/components/composed': typeof ComponentsComposedRouteWithChildren
  '/components/icons': typeof ComponentsIconsRoute
  '/components/integrations': typeof ComponentsIntegrationsRouteWithChildren
  '/components/primitives': typeof ComponentsPrimitivesRouteWithChildren
  '/components/': typeof ComponentsIndexRoute
  '/components/composed/accordion': typeof ComponentsComposedAccordionRoute
  '/components/composed/action-modal': typeof ComponentsComposedActionModalRoute
  '/components/composed/banner': typeof ComponentsComposedBannerRoute
  '/components/composed/callout': typeof ComponentsComposedCalloutRoute
  '/components/composed/dialog': typeof ComponentsComposedDialogRoute
  '/components/composed/drawer': typeof ComponentsComposedDrawerRoute
  '/components/composed/dropdown': typeof ComponentsComposedDropdownRoute
  '/components/composed/file-upload': typeof ComponentsComposedFileUploadRoute
  '/components/composed/hover-card': typeof ComponentsComposedHoverCardRoute
  '/components/composed/message-bubble': typeof ComponentsComposedMessageBubbleRoute
  '/components/composed/metric-input': typeof ComponentsComposedMetricInputRoute
  '/components/composed/password-strength-meter': typeof ComponentsComposedPasswordStrengthMeterRoute
  '/components/composed/popover': typeof ComponentsComposedPopoverRoute
  '/components/composed/scroll-area': typeof ComponentsComposedScrollAreaRoute
  '/components/composed/tabs': typeof ComponentsComposedTabsRoute
  '/components/composed/toast': typeof ComponentsComposedToastRoute
  '/components/composed/tooltip': typeof ComponentsComposedTooltipRoute
  '/components/integrations/data-table': typeof ComponentsIntegrationsDataTableRoute
  '/components/primitives/badge': typeof ComponentsPrimitivesBadgeRoute
  '/components/primitives/bars': typeof ComponentsPrimitivesBarsRoute
  '/components/primitives/box': typeof ComponentsPrimitivesBoxRoute
  '/components/primitives/button': typeof ComponentsPrimitivesButtonRoute
  '/components/primitives/checkbox': typeof ComponentsPrimitivesCheckboxRoute
  '/components/primitives/count-badge': typeof ComponentsPrimitivesCountBadgeRoute
  '/components/primitives/display': typeof ComponentsPrimitivesDisplayRoute
  '/components/primitives/divider': typeof ComponentsPrimitivesDividerRoute
  '/components/primitives/grid': typeof ComponentsPrimitivesGridRoute
  '/components/primitives/heading': typeof ComponentsPrimitivesHeadingRoute
  '/components/primitives/input': typeof ComponentsPrimitivesInputRoute
  '/components/primitives/list': typeof ComponentsPrimitivesListRoute
  '/components/primitives/progress-bar': typeof ComponentsPrimitivesProgressBarRoute
  '/components/primitives/radio': typeof ComponentsPrimitivesRadioRoute
  '/components/primitives/row': typeof ComponentsPrimitivesRowRoute
  '/components/primitives/select': typeof ComponentsPrimitivesSelectRoute
  '/components/primitives/slider': typeof ComponentsPrimitivesSliderRoute
  '/components/primitives/stack': typeof ComponentsPrimitivesStackRoute
  '/components/primitives/status-dot': typeof ComponentsPrimitivesStatusDotRoute
  '/components/primitives/switch': typeof ComponentsPrimitivesSwitchRoute
  '/components/primitives/table': typeof ComponentsPrimitivesTableRoute
  '/components/primitives/text': typeof ComponentsPrimitivesTextRoute
  '/components/primitives/textarea': typeof ComponentsPrimitivesTextareaRoute
  '/components/primitives/verified-badge': typeof ComponentsPrimitivesVerifiedBadgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-guidelines'
    | '/components'
    | '/forms'
    | '/hooks'
    | '/libs'
    | '/playground'
    | '/providers'
    | '/components/composed'
    | '/components/icons'
    | '/components/integrations'
    | '/components/primitives'
    | '/components/'
    | '/components/composed/accordion'
    | '/components/composed/action-modal'
    | '/components/composed/banner'
    | '/components/composed/callout'
    | '/components/composed/dialog'
    | '/components/composed/drawer'
    | '/components/composed/dropdown'
    | '/components/composed/file-upload'
    | '/components/composed/hover-card'
    | '/components/composed/message-bubble'
    | '/components/composed/metric-input'
    | '/components/composed/password-strength-meter'
    | '/components/composed/popover'
    | '/components/composed/scroll-area'
    | '/components/composed/tabs'
    | '/components/composed/toast'
    | '/components/composed/tooltip'
    | '/components/integrations/data-table'
    | '/components/primitives/badge'
    | '/components/primitives/bars'
    | '/components/primitives/box'
    | '/components/primitives/button'
    | '/components/primitives/checkbox'
    | '/components/primitives/count-badge'
    | '/components/primitives/display'
    | '/components/primitives/divider'
    | '/components/primitives/grid'
    | '/components/primitives/heading'
    | '/components/primitives/input'
    | '/components/primitives/list'
    | '/components/primitives/progress-bar'
    | '/components/primitives/radio'
    | '/components/primitives/row'
    | '/components/primitives/select'
    | '/components/primitives/slider'
    | '/components/primitives/stack'
    | '/components/primitives/status-dot'
    | '/components/primitives/switch'
    | '/components/primitives/table'
    | '/components/primitives/text'
    | '/components/primitives/textarea'
    | '/components/primitives/verified-badge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-guidelines'
    | '/forms'
    | '/hooks'
    | '/libs'
    | '/playground'
    | '/providers'
    | '/components/composed'
    | '/components/icons'
    | '/components/integrations'
    | '/components/primitives'
    | '/components'
    | '/components/composed/accordion'
    | '/components/composed/action-modal'
    | '/components/composed/banner'
    | '/components/composed/callout'
    | '/components/composed/dialog'
    | '/components/composed/drawer'
    | '/components/composed/dropdown'
    | '/components/composed/file-upload'
    | '/components/composed/hover-card'
    | '/components/composed/message-bubble'
    | '/components/composed/metric-input'
    | '/components/composed/password-strength-meter'
    | '/components/composed/popover'
    | '/components/composed/scroll-area'
    | '/components/composed/tabs'
    | '/components/composed/toast'
    | '/components/composed/tooltip'
    | '/components/integrations/data-table'
    | '/components/primitives/badge'
    | '/components/primitives/bars'
    | '/components/primitives/box'
    | '/components/primitives/button'
    | '/components/primitives/checkbox'
    | '/components/primitives/count-badge'
    | '/components/primitives/display'
    | '/components/primitives/divider'
    | '/components/primitives/grid'
    | '/components/primitives/heading'
    | '/components/primitives/input'
    | '/components/primitives/list'
    | '/components/primitives/progress-bar'
    | '/components/primitives/radio'
    | '/components/primitives/row'
    | '/components/primitives/select'
    | '/components/primitives/slider'
    | '/components/primitives/stack'
    | '/components/primitives/status-dot'
    | '/components/primitives/switch'
    | '/components/primitives/table'
    | '/components/primitives/text'
    | '/components/primitives/textarea'
    | '/components/primitives/verified-badge'
  id:
    | '__root__'
    | '/'
    | '/brand-guidelines'
    | '/components'
    | '/forms'
    | '/hooks'
    | '/libs'
    | '/playground'
    | '/providers'
    | '/components/composed'
    | '/components/icons'
    | '/components/integrations'
    | '/components/primitives'
    | '/components/'
    | '/components/composed/accordion'
    | '/components/composed/action-modal'
    | '/components/composed/banner'
    | '/components/composed/callout'
    | '/components/composed/dialog'
    | '/components/composed/drawer'
    | '/components/composed/dropdown'
    | '/components/composed/file-upload'
    | '/components/composed/hover-card'
    | '/components/composed/message-bubble'
    | '/components/composed/metric-input'
    | '/components/composed/password-strength-meter'
    | '/components/composed/popover'
    | '/components/composed/scroll-area'
    | '/components/composed/tabs'
    | '/components/composed/toast'
    | '/components/composed/tooltip'
    | '/components/integrations/data-table'
    | '/components/primitives/badge'
    | '/components/primitives/bars'
    | '/components/primitives/box'
    | '/components/primitives/button'
    | '/components/primitives/checkbox'
    | '/components/primitives/count-badge'
    | '/components/primitives/display'
    | '/components/primitives/divider'
    | '/components/primitives/grid'
    | '/components/primitives/heading'
    | '/components/primitives/input'
    | '/components/primitives/list'
    | '/components/primitives/progress-bar'
    | '/components/primitives/radio'
    | '/components/primitives/row'
    | '/components/primitives/select'
    | '/components/primitives/slider'
    | '/components/primitives/stack'
    | '/components/primitives/status-dot'
    | '/components/primitives/switch'
    | '/components/primitives/table'
    | '/components/primitives/text'
    | '/components/primitives/textarea'
    | '/components/primitives/verified-badge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandGuidelinesRoute: typeof BrandGuidelinesRoute
  ComponentsRoute: typeof ComponentsRouteWithChildren
  FormsRoute: typeof FormsRoute
  HooksRoute: typeof HooksRoute
  LibsRoute: typeof LibsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProvidersRoute: typeof ProvidersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-guidelines': {
      id: '/brand-guidelines'
      path: '/brand-guidelines'
      fullPath: '/brand-guidelines'
      preLoaderRoute: typeof BrandGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks': {
      id: '/hooks'
      path: '/hooks'
      fullPath: '/hooks'
      preLoaderRoute: typeof HooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libs': {
      id: '/libs'
      path: '/libs'
      fullPath: '/libs'
      preLoaderRoute: typeof LibsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/composed': {
      id: '/components/composed'
      path: '/composed'
      fullPath: '/components/composed'
      preLoaderRoute: typeof ComponentsComposedRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/icons': {
      id: '/components/icons'
      path: '/icons'
      fullPath: '/components/icons'
      preLoaderRoute: typeof ComponentsIconsRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/integrations': {
      id: '/components/integrations'
      path: '/integrations'
      fullPath: '/components/integrations'
      preLoaderRoute: typeof ComponentsIntegrationsRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/primitives': {
      id: '/components/primitives'
      path: '/primitives'
      fullPath: '/components/primitives'
      preLoaderRoute: typeof ComponentsPrimitivesRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/composed/accordion': {
      id: '/components/composed/accordion'
      path: '/accordion'
      fullPath: '/components/composed/accordion'
      preLoaderRoute: typeof ComponentsComposedAccordionRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/action-modal': {
      id: '/components/composed/action-modal'
      path: '/action-modal'
      fullPath: '/components/composed/action-modal'
      preLoaderRoute: typeof ComponentsComposedActionModalRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/banner': {
      id: '/components/composed/banner'
      path: '/banner'
      fullPath: '/components/composed/banner'
      preLoaderRoute: typeof ComponentsComposedBannerRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/callout': {
      id: '/components/composed/callout'
      path: '/callout'
      fullPath: '/components/composed/callout'
      preLoaderRoute: typeof ComponentsComposedCalloutRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/dialog': {
      id: '/components/composed/dialog'
      path: '/dialog'
      fullPath: '/components/composed/dialog'
      preLoaderRoute: typeof ComponentsComposedDialogRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/drawer': {
      id: '/components/composed/drawer'
      path: '/drawer'
      fullPath: '/components/composed/drawer'
      preLoaderRoute: typeof ComponentsComposedDrawerRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/dropdown': {
      id: '/components/composed/dropdown'
      path: '/dropdown'
      fullPath: '/components/composed/dropdown'
      preLoaderRoute: typeof ComponentsComposedDropdownRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/file-upload': {
      id: '/components/composed/file-upload'
      path: '/file-upload'
      fullPath: '/components/composed/file-upload'
      preLoaderRoute: typeof ComponentsComposedFileUploadRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/hover-card': {
      id: '/components/composed/hover-card'
      path: '/hover-card'
      fullPath: '/components/composed/hover-card'
      preLoaderRoute: typeof ComponentsComposedHoverCardRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/message-bubble': {
      id: '/components/composed/message-bubble'
      path: '/message-bubble'
      fullPath: '/components/composed/message-bubble'
      preLoaderRoute: typeof ComponentsComposedMessageBubbleRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/metric-input': {
      id: '/components/composed/metric-input'
      path: '/metric-input'
      fullPath: '/components/composed/metric-input'
      preLoaderRoute: typeof ComponentsComposedMetricInputRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/password-strength-meter': {
      id: '/components/composed/password-strength-meter'
      path: '/password-strength-meter'
      fullPath: '/components/composed/password-strength-meter'
      preLoaderRoute: typeof ComponentsComposedPasswordStrengthMeterRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/popover': {
      id: '/components/composed/popover'
      path: '/popover'
      fullPath: '/components/composed/popover'
      preLoaderRoute: typeof ComponentsComposedPopoverRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/scroll-area': {
      id: '/components/composed/scroll-area'
      path: '/scroll-area'
      fullPath: '/components/composed/scroll-area'
      preLoaderRoute: typeof ComponentsComposedScrollAreaRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/tabs': {
      id: '/components/composed/tabs'
      path: '/tabs'
      fullPath: '/components/composed/tabs'
      preLoaderRoute: typeof ComponentsComposedTabsRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/toast': {
      id: '/components/composed/toast'
      path: '/toast'
      fullPath: '/components/composed/toast'
      preLoaderRoute: typeof ComponentsComposedToastRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/composed/tooltip': {
      id: '/components/composed/tooltip'
      path: '/tooltip'
      fullPath: '/components/composed/tooltip'
      preLoaderRoute: typeof ComponentsComposedTooltipRouteImport
      parentRoute: typeof ComponentsComposedRoute
    }
    '/components/integrations/data-table': {
      id: '/components/integrations/data-table'
      path: '/data-table'
      fullPath: '/components/integrations/data-table'
      preLoaderRoute: typeof ComponentsIntegrationsDataTableRouteImport
      parentRoute: typeof ComponentsIntegrationsRoute
    }
    '/components/primitives/badge': {
      id: '/components/primitives/badge'
      path: '/badge'
      fullPath: '/components/primitives/badge'
      preLoaderRoute: typeof ComponentsPrimitivesBadgeRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/bars': {
      id: '/components/primitives/bars'
      path: '/bars'
      fullPath: '/components/primitives/bars'
      preLoaderRoute: typeof ComponentsPrimitivesBarsRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/box': {
      id: '/components/primitives/box'
      path: '/box'
      fullPath: '/components/primitives/box'
      preLoaderRoute: typeof ComponentsPrimitivesBoxRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/button': {
      id: '/components/primitives/button'
      path: '/button'
      fullPath: '/components/primitives/button'
      preLoaderRoute: typeof ComponentsPrimitivesButtonRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/checkbox': {
      id: '/components/primitives/checkbox'
      path: '/checkbox'
      fullPath: '/components/primitives/checkbox'
      preLoaderRoute: typeof ComponentsPrimitivesCheckboxRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/count-badge': {
      id: '/components/primitives/count-badge'
      path: '/count-badge'
      fullPath: '/components/primitives/count-badge'
      preLoaderRoute: typeof ComponentsPrimitivesCountBadgeRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/display': {
      id: '/components/primitives/display'
      path: '/display'
      fullPath: '/components/primitives/display'
      preLoaderRoute: typeof ComponentsPrimitivesDisplayRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/divider': {
      id: '/components/primitives/divider'
      path: '/divider'
      fullPath: '/components/primitives/divider'
      preLoaderRoute: typeof ComponentsPrimitivesDividerRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/grid': {
      id: '/components/primitives/grid'
      path: '/grid'
      fullPath: '/components/primitives/grid'
      preLoaderRoute: typeof ComponentsPrimitivesGridRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/heading': {
      id: '/components/primitives/heading'
      path: '/heading'
      fullPath: '/components/primitives/heading'
      preLoaderRoute: typeof ComponentsPrimitivesHeadingRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/input': {
      id: '/components/primitives/input'
      path: '/input'
      fullPath: '/components/primitives/input'
      preLoaderRoute: typeof ComponentsPrimitivesInputRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/list': {
      id: '/components/primitives/list'
      path: '/list'
      fullPath: '/components/primitives/list'
      preLoaderRoute: typeof ComponentsPrimitivesListRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/progress-bar': {
      id: '/components/primitives/progress-bar'
      path: '/progress-bar'
      fullPath: '/components/primitives/progress-bar'
      preLoaderRoute: typeof ComponentsPrimitivesProgressBarRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/radio': {
      id: '/components/primitives/radio'
      path: '/radio'
      fullPath: '/components/primitives/radio'
      preLoaderRoute: typeof ComponentsPrimitivesRadioRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/row': {
      id: '/components/primitives/row'
      path: '/row'
      fullPath: '/components/primitives/row'
      preLoaderRoute: typeof ComponentsPrimitivesRowRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/select': {
      id: '/components/primitives/select'
      path: '/select'
      fullPath: '/components/primitives/select'
      preLoaderRoute: typeof ComponentsPrimitivesSelectRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/slider': {
      id: '/components/primitives/slider'
      path: '/slider'
      fullPath: '/components/primitives/slider'
      preLoaderRoute: typeof ComponentsPrimitivesSliderRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/stack': {
      id: '/components/primitives/stack'
      path: '/stack'
      fullPath: '/components/primitives/stack'
      preLoaderRoute: typeof ComponentsPrimitivesStackRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/status-dot': {
      id: '/components/primitives/status-dot'
      path: '/status-dot'
      fullPath: '/components/primitives/status-dot'
      preLoaderRoute: typeof ComponentsPrimitivesStatusDotRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/switch': {
      id: '/components/primitives/switch'
      path: '/switch'
      fullPath: '/components/primitives/switch'
      preLoaderRoute: typeof ComponentsPrimitivesSwitchRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/table': {
      id: '/components/primitives/table'
      path: '/table'
      fullPath: '/components/primitives/table'
      preLoaderRoute: typeof ComponentsPrimitivesTableRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/text': {
      id: '/components/primitives/text'
      path: '/text'
      fullPath: '/components/primitives/text'
      preLoaderRoute: typeof ComponentsPrimitivesTextRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/textarea': {
      id: '/components/primitives/textarea'
      path: '/textarea'
      fullPath: '/components/primitives/textarea'
      preLoaderRoute: typeof ComponentsPrimitivesTextareaRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
    '/components/primitives/verified-badge': {
      id: '/components/primitives/verified-badge'
      path: '/verified-badge'
      fullPath: '/components/primitives/verified-badge'
      preLoaderRoute: typeof ComponentsPrimitivesVerifiedBadgeRouteImport
      parentRoute: typeof ComponentsPrimitivesRoute
    }
  }
}

interface ComponentsComposedRouteChildren {
  ComponentsComposedAccordionRoute: typeof ComponentsComposedAccordionRoute
  ComponentsComposedActionModalRoute: typeof ComponentsComposedActionModalRoute
  ComponentsComposedBannerRoute: typeof ComponentsComposedBannerRoute
  ComponentsComposedCalloutRoute: typeof ComponentsComposedCalloutRoute
  ComponentsComposedDialogRoute: typeof ComponentsComposedDialogRoute
  ComponentsComposedDrawerRoute: typeof ComponentsComposedDrawerRoute
  ComponentsComposedDropdownRoute: typeof ComponentsComposedDropdownRoute
  ComponentsComposedFileUploadRoute: typeof ComponentsComposedFileUploadRoute
  ComponentsComposedHoverCardRoute: typeof ComponentsComposedHoverCardRoute
  ComponentsComposedMessageBubbleRoute: typeof ComponentsComposedMessageBubbleRoute
  ComponentsComposedMetricInputRoute: typeof ComponentsComposedMetricInputRoute
  ComponentsComposedPasswordStrengthMeterRoute: typeof ComponentsComposedPasswordStrengthMeterRoute
  ComponentsComposedPopoverRoute: typeof ComponentsComposedPopoverRoute
  ComponentsComposedScrollAreaRoute: typeof ComponentsComposedScrollAreaRoute
  ComponentsComposedTabsRoute: typeof ComponentsComposedTabsRoute
  ComponentsComposedToastRoute: typeof ComponentsComposedToastRoute
  ComponentsComposedTooltipRoute: typeof ComponentsComposedTooltipRoute
}

const ComponentsComposedRouteChildren: ComponentsComposedRouteChildren = {
  ComponentsComposedAccordionRoute: ComponentsComposedAccordionRoute,
  ComponentsComposedActionModalRoute: ComponentsComposedActionModalRoute,
  ComponentsComposedBannerRoute: ComponentsComposedBannerRoute,
  ComponentsComposedCalloutRoute: ComponentsComposedCalloutRoute,
  ComponentsComposedDialogRoute: ComponentsComposedDialogRoute,
  ComponentsComposedDrawerRoute: ComponentsComposedDrawerRoute,
  ComponentsComposedDropdownRoute: ComponentsComposedDropdownRoute,
  ComponentsComposedFileUploadRoute: ComponentsComposedFileUploadRoute,
  ComponentsComposedHoverCardRoute: ComponentsComposedHoverCardRoute,
  ComponentsComposedMessageBubbleRoute: ComponentsComposedMessageBubbleRoute,
  ComponentsComposedMetricInputRoute: ComponentsComposedMetricInputRoute,
  ComponentsComposedPasswordStrengthMeterRoute:
    ComponentsComposedPasswordStrengthMeterRoute,
  ComponentsComposedPopoverRoute: ComponentsComposedPopoverRoute,
  ComponentsComposedScrollAreaRoute: ComponentsComposedScrollAreaRoute,
  ComponentsComposedTabsRoute: ComponentsComposedTabsRoute,
  ComponentsComposedToastRoute: ComponentsComposedToastRoute,
  ComponentsComposedTooltipRoute: ComponentsComposedTooltipRoute,
}

const ComponentsComposedRouteWithChildren =
  ComponentsComposedRoute._addFileChildren(ComponentsComposedRouteChildren)

interface ComponentsIntegrationsRouteChildren {
  ComponentsIntegrationsDataTableRoute: typeof ComponentsIntegrationsDataTableRoute
}

const ComponentsIntegrationsRouteChildren: ComponentsIntegrationsRouteChildren =
  {
    ComponentsIntegrationsDataTableRoute: ComponentsIntegrationsDataTableRoute,
  }

const ComponentsIntegrationsRouteWithChildren =
  ComponentsIntegrationsRoute._addFileChildren(
    ComponentsIntegrationsRouteChildren,
  )

interface ComponentsPrimitivesRouteChildren {
  ComponentsPrimitivesBadgeRoute: typeof ComponentsPrimitivesBadgeRoute
  ComponentsPrimitivesBarsRoute: typeof ComponentsPrimitivesBarsRoute
  ComponentsPrimitivesBoxRoute: typeof ComponentsPrimitivesBoxRoute
  ComponentsPrimitivesButtonRoute: typeof ComponentsPrimitivesButtonRoute
  ComponentsPrimitivesCheckboxRoute: typeof ComponentsPrimitivesCheckboxRoute
  ComponentsPrimitivesCountBadgeRoute: typeof ComponentsPrimitivesCountBadgeRoute
  ComponentsPrimitivesDisplayRoute: typeof ComponentsPrimitivesDisplayRoute
  ComponentsPrimitivesDividerRoute: typeof ComponentsPrimitivesDividerRoute
  ComponentsPrimitivesGridRoute: typeof ComponentsPrimitivesGridRoute
  ComponentsPrimitivesHeadingRoute: typeof ComponentsPrimitivesHeadingRoute
  ComponentsPrimitivesInputRoute: typeof ComponentsPrimitivesInputRoute
  ComponentsPrimitivesListRoute: typeof ComponentsPrimitivesListRoute
  ComponentsPrimitivesProgressBarRoute: typeof ComponentsPrimitivesProgressBarRoute
  ComponentsPrimitivesRadioRoute: typeof ComponentsPrimitivesRadioRoute
  ComponentsPrimitivesRowRoute: typeof ComponentsPrimitivesRowRoute
  ComponentsPrimitivesSelectRoute: typeof ComponentsPrimitivesSelectRoute
  ComponentsPrimitivesSliderRoute: typeof ComponentsPrimitivesSliderRoute
  ComponentsPrimitivesStackRoute: typeof ComponentsPrimitivesStackRoute
  ComponentsPrimitivesStatusDotRoute: typeof ComponentsPrimitivesStatusDotRoute
  ComponentsPrimitivesSwitchRoute: typeof ComponentsPrimitivesSwitchRoute
  ComponentsPrimitivesTableRoute: typeof ComponentsPrimitivesTableRoute
  ComponentsPrimitivesTextRoute: typeof ComponentsPrimitivesTextRoute
  ComponentsPrimitivesTextareaRoute: typeof ComponentsPrimitivesTextareaRoute
  ComponentsPrimitivesVerifiedBadgeRoute: typeof ComponentsPrimitivesVerifiedBadgeRoute
}

const ComponentsPrimitivesRouteChildren: ComponentsPrimitivesRouteChildren = {
  ComponentsPrimitivesBadgeRoute: ComponentsPrimitivesBadgeRoute,
  ComponentsPrimitivesBarsRoute: ComponentsPrimitivesBarsRoute,
  ComponentsPrimitivesBoxRoute: ComponentsPrimitivesBoxRoute,
  ComponentsPrimitivesButtonRoute: ComponentsPrimitivesButtonRoute,
  ComponentsPrimitivesCheckboxRoute: ComponentsPrimitivesCheckboxRoute,
  ComponentsPrimitivesCountBadgeRoute: ComponentsPrimitivesCountBadgeRoute,
  ComponentsPrimitivesDisplayRoute: ComponentsPrimitivesDisplayRoute,
  ComponentsPrimitivesDividerRoute: ComponentsPrimitivesDividerRoute,
  ComponentsPrimitivesGridRoute: ComponentsPrimitivesGridRoute,
  ComponentsPrimitivesHeadingRoute: ComponentsPrimitivesHeadingRoute,
  ComponentsPrimitivesInputRoute: ComponentsPrimitivesInputRoute,
  ComponentsPrimitivesListRoute: ComponentsPrimitivesListRoute,
  ComponentsPrimitivesProgressBarRoute: ComponentsPrimitivesProgressBarRoute,
  ComponentsPrimitivesRadioRoute: ComponentsPrimitivesRadioRoute,
  ComponentsPrimitivesRowRoute: ComponentsPrimitivesRowRoute,
  ComponentsPrimitivesSelectRoute: ComponentsPrimitivesSelectRoute,
  ComponentsPrimitivesSliderRoute: ComponentsPrimitivesSliderRoute,
  ComponentsPrimitivesStackRoute: ComponentsPrimitivesStackRoute,
  ComponentsPrimitivesStatusDotRoute: ComponentsPrimitivesStatusDotRoute,
  ComponentsPrimitivesSwitchRoute: ComponentsPrimitivesSwitchRoute,
  ComponentsPrimitivesTableRoute: ComponentsPrimitivesTableRoute,
  ComponentsPrimitivesTextRoute: ComponentsPrimitivesTextRoute,
  ComponentsPrimitivesTextareaRoute: ComponentsPrimitivesTextareaRoute,
  ComponentsPrimitivesVerifiedBadgeRoute:
    ComponentsPrimitivesVerifiedBadgeRoute,
}

const ComponentsPrimitivesRouteWithChildren =
  ComponentsPrimitivesRoute._addFileChildren(ComponentsPrimitivesRouteChildren)

interface ComponentsRouteChildren {
  ComponentsComposedRoute: typeof ComponentsComposedRouteWithChildren
  ComponentsIconsRoute: typeof ComponentsIconsRoute
  ComponentsIntegrationsRoute: typeof ComponentsIntegrationsRouteWithChildren
  ComponentsPrimitivesRoute: typeof ComponentsPrimitivesRouteWithChildren
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

const ComponentsRouteChildren: ComponentsRouteChildren = {
  ComponentsComposedRoute: ComponentsComposedRouteWithChildren,
  ComponentsIconsRoute: ComponentsIconsRoute,
  ComponentsIntegrationsRoute: ComponentsIntegrationsRouteWithChildren,
  ComponentsPrimitivesRoute: ComponentsPrimitivesRouteWithChildren,
  ComponentsIndexRoute: ComponentsIndexRoute,
}

const ComponentsRouteWithChildren = ComponentsRoute._addFileChildren(
  ComponentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandGuidelinesRoute: BrandGuidelinesRoute,
  ComponentsRoute: ComponentsRouteWithChildren,
  FormsRoute: FormsRoute,
  HooksRoute: HooksRoute,
  LibsRoute: LibsRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProvidersRoute: ProvidersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
